export const BRIEF_LIST_REQUEST = 'BRIEF_LIST_REQUEST';
export const BRIEF_LIST_SUCCESS = 'BRIEF_LIST_SUCCESS';
export const BRIEF_LIST_FAIL = 'BRIEF_LIST_FAIL';

export const BRIEF_GET_REQUEST = 'BRIEF_GET_REQUEST';
export const BRIEF_GET_SUCCESS = 'BRIEF_GET_SUCCESS';
export const BRIEF_GET_FAIL = 'BRIEF_GET_FAIL';

export const BRIEF_ADD_REQUEST = 'BRIEF_ADD_REQUEST';
export const BRIEF_ADD_SUCCESS = 'BRIEF_ADD_SUCCESS';
export const BRIEF_ADD_FAIL = 'BRIEF_ADD_FAIL';

export const BRIEF_DATA_RESET = 'BRIEF_DATA_RESET';

export const BRIEF_DELETE_REQUEST = 'BRIEF_DELETE_REQUEST';
export const BRIEF_DELETE_SUCCESS = 'BRIEF_DELETE_SUCCESS';
export const BRIEF_DELETE_FAIL = 'BRIEF_DELETE_FAIL';
