export const PROJECT_ALL_REQUEST = 'PROJECT_ALL_REQUEST';
export const PROJECT_ALL_SUCCESS = 'PROJECT_ALL_SUCCESS';
export const PROJECT_ALL_FAIL = 'PROJECT_ALL_FAIL';

export const PROJECT_CURRENT_REQUEST = 'PROJECT_CURRENT_REQUEST';
export const PROJECT_CURRENT_SUCCESS = 'PROJECT_CURRENT_SUCCESS';
export const PROJECT_CURRENT_FAIL = 'PROJECT_CURRENT_FAIL';
export const PROJECT_CURRENT_SELECT = 'PROJECT_CURRENT_SELECT';

export const PROJECT_CREATE_REQUEST = 'PROJECT_CREATE_REQUEST';
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS';
export const PROJECT_CREATE_RESET = 'PROJECT_CREATE_RESET';
export const PROJECT_CREATE_FAIL = 'PROJECT_CREATE_FAIL';

export const PROJECT_DELETE_REQUEST = 'PROJECT_DELETE_REQUEST';
export const PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS';
export const PROJECT_DELETE_FAIL = 'PROJECT_DELETE_FAIL';

export const PROJECT_DETAILS_REQUEST = 'PROJECT_DETAILS_REQUEST';
export const PROJECT_DETAILS_SUCCESS = 'PROJECT_DETAILS_SUCCESS';
export const PROJECT_DETAILS_FAIL = 'PROJECT_DETAILS_FAIL';

export const PROJECT_SELECT = 'PROJECT_SELECT';

export const PROJECT_QUARTER_SET = 'PROJECT_QUARTER_SET';
export const PROJECT_QUARTER_GET = 'PROJECT_QUARTER_GET';
